### PR TITLE
Document change.select2 on event list

### PR DESCRIPTION
**Pull request by William-H-M**
Added as time to time is need it to avoid confusion between events. Base on https://github.com/select2/select2/issues/3620#issuecomment-181600117
and commit https://github.com/select2/select2/commit/7f8e9dc62a847ef63d38b8cd8f6e13f31bbb2115
Note: should an example be added?

### CODE REVIEW

**Comment by alexweissman** [comment]
Thanks!  It's actually documented here: https://select2.org/programmatic-control/add-select-clear-items#limiting-the-scope-of-the-change-event.

I'm actually not sure if we should add it directly to the list of events, because those are all events that _Select2_ triggers.  `change.select2`, on the other hand, is an event that the _consumer_ triggers _on_ Select2.

**Comment by William-H-M** [comment]
Hi, @alexweissman but the thing is that be itself is an "event", somehow because as you said it's triggered by the user, but it'll be useful to have it on the list as an event to which select react, and of course could be used as a "refresh" sometimes to avoid unwanted behavior.

Of course this will be left at your discretion :)

**Comment by alexweissman** [comment]
Let's break it into two sections then:

- Events triggered by Select2
- Events that can be triggered on Select2

**Comment by William-H-M** [comment]
Seems good to me, so I'll be closing as has been decided, have a nice day :)

**Comment by alexweissman** [comment]
Ok, I have updated and reorganized the events docs a bit, as inspired by your comments: https://select2.org/programmatic-control/events

**Pull request closed without merging**
